---
# file: roles/k8s_admin/tasks/delete.yml

- include_tasks: "delete-bind.yml"
  when: task == "bind" or task == "all"

- include_tasks: "delete-openvpn.yml"
  when: task == "openvpn" or task == "all"

- include_tasks: "delete-others.yml"
  when: task == "others" or task == "all"
