---
# file: roles/k8s_core/tasks/delete-ui.yml

- name: rm file /home/kubeadmin/cfssl/dashboard-csr.json
  file:
    path: /home/kubeadmin/cfssl/dashboard-csr.json
    state: absent

- name: rm file /home/kubeadmin/cfssl/dashboard.pem
  file:
    path: /home/kubeadmin/cfssl/dashboard.pem
    state: absent

- name: rm file /home/kubeadmin/cfssl/dashboard-key.pem
  file:
    path: /home/kubeadmin/cfssl/dashboard-key.pem
    state: absent

- name: rm file /home/kubeadmin/cfssl/dashboard.csr
  file:
    path: /home/kubeadmin/cfssl/dashboard.csr
    state: absent

- name: delete dashboard nginx ingress
  shell: kubectl delete -f /home/kubeadmin/dashboard/k8s-dashboard-nginx.yaml
  become: true
  become_user: kubeadmin
  tags : core, dashboard

- name: delete secret tls-secret
  shell: kubectl delete secret tls tls-secret -n kubernetes-dashboard
  become: true
  become_user: kubeadmin
