---
# file: roles/k8s_core/tasks/untaint-master-nodes.yml

- name: untaint master nodes
  shell: kubectl taint nodes {{ item }} node-role.kubernetes.io/master-
  become: true
  become_user: kubeadmin
  ignore_errors: true
  with_items: "{{ k8s.master.untaint_master_nodes }}"

